services:
  - type: web
    name: yeet-bank-frontend
    runtime: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
